// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22kX7rcWIM9elTK4IamqHa1ypVxVbkoU',
    appId: '1:768195037773:android:4c7ccb027f94e49f52aa04',
    messagingSenderId: '768195037773',
    projectId: 'zechat-584ae',
    storageBucket: 'zechat-584ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwpjzteLmkElvcBR9f1-csV099iULOyqk',
    appId: '1:768195037773:ios:348e0a11f198ae5c52aa04',
    messagingSenderId: '768195037773',
    projectId: 'zechat-584ae',
    storageBucket: 'zechat-584ae.appspot.com',
    androidClientId: '768195037773-eaii3sapfvt5jrhc6ro4qt0nstfmihav.apps.googleusercontent.com',
    iosClientId: '768195037773-t2mumaej8bibntpe45m87uecolgqtkas.apps.googleusercontent.com',
    iosBundleId: 'com.example.zechat',
  );
}
